FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Get It Done To Do List

A to do list item object contains the following attributes:
+ listid : integer      The identifier of the to do list.  For this early version we only support a single list with listid=0.
+ itemid : integer      The identifier of the to do list item.  This value is unique across the entire application.
+ name : string         A textual name for the to do list item.
+ status : integer      Whether the item is complete (1)  or incomplete (0)

# Group Items

## Items Collection [/items]

### List All Items [GET]

The application currently only supports a single to do list, but in 
the future we will support multiple to do lists, and so this value 
will become more important later.

+ Response 200 (application/json)

        [
            {
                "listid": 0,
                "itemid": 1001,
                "name": "Buy milk",
                "status": 0
            }
        ]

### Create a New Item [POST]

This method will create a to do list item on a specific to do list.

+ Request (application/json)

        {
            "name": "Buy milk"
        }

+ Response 201 (application/json)

    + Headers

            Location: /items/2

    + Body

            {
                "itemid": 1001
            }

+ Response 500 (application/json)

        {
            "error": "Could not create to do list item"
        }


### Updating a New Item [PUT]

This method will update a to do list item on a specific to do list.

+ Request (application/json)

        {
            "itemid": 1001,
            "name": "Buy whole milk",
            "status": 1
        }

+ Response 200 (application/json)

    + Headers

            Location: /items/2

    + Body

            {
                "itemid": 1001
            }

+ Response 500 (application/json)

        {
            "error": "Could not create to do list item"
        }

### Deleting an Item [DELETE]

This method will delete a to do list item on a specific to do list.

+ Request (application/json)

        {
            "itemid": 1001
        }

+ Response 204 (plain text)

    + Headers

            Location: /items/2


+ Response 500 (application/json)

        {
            "error": "Could not delete to do list item"
        }